about page
acmucsd/space-2022 pull request #1
Opened 2022-08-11 03:06 UTC by Jvil26

2022-08-14 11:06 UTC, farisashai requested changes
Overall page looks really clean - nice job! I left a couple comments mainly about code style we want to adhere to. 

After that, I'm not sure if we wanted to keep the website layout all in a single page from the Figma design so I would clarify with Kait and Sam about the decision to keep the about page on a separate `/about` route and handle navigation that way. I'm not going to comment on CSS right now - I think it'll be good to fix some of the bigger changes first and then I can review it again to fine tune it the actual UI implementation.

2022-08-14 11:06 UTC, farisashai commented on pages/about.tsx
> +import React from "react";
nitpick: we don't need to include this line in nextjs

2022-08-14 11:06 UTC, farisashai commented on src/styles/Home.module.scss
> +.about__container {
You might have seen this code style being used on the main website or other ACM repos. This convention is called [BEM](https://css-tricks.com/bem-101/) (Block Element Modifier) naming and it's popular because it's a consistent way of avoiding naming collisions between CSS class names in different files. It's actually outdated now since we're using CSS modules which guarantee that we don't run into any collisions. Having a className of `.container` in two different `.module.scss `files is totally okay and won't break anything! Let's try to keep the class names as simple as possible.

2022-08-14 11:06 UTC, farisashai commented on src/sections/About/style.module.scss
> +  &__description {
Same as the last comment for all of the CSS selectors in this file - change to `.description` or something like that to keep it simple. The & syntax for child selectors gets very difficult to read and a bit confusing to maintain. A lot of our code is written in this old style across the main website and that's a big refactor we need to fix someday :(

2022-08-14 11:06 UTC, farisashai commented on src/components/TsParticles/style.module.scss
> +#tsparticles {
Nitpick: There aren't many practical use cases to use IDs in React. CSS selectors should be used for all component styling since components are reusable and not unique by definition. If you need to select a element inside of a React component, I would look into the `useRef` hook. If the file is empty, we can delete it

2022-08-14 11:06 UTC, farisashai commented on src/components/TsParticles/index.tsx
> +import "./style.module.scss";
Nitpick: CSS **modules** should be imported with a name (ex: `import style from './style.module.scss'`). In this case, we can delete the file if it's empty.

2022-08-14 11:06 UTC, farisashai commented on src/components/TsParticles/index.tsx
> +    console.log(container);
Nitpick: Try to delete console.log statements before pushing code to a real website after you're done testing the behavior.

2022-08-14 11:06 UTC, farisashai commented on src/components/TsParticles/index.tsx
> +  const particlesLoaded = async (container: any) => {
Nitpick: This is totally just a coding style decision but a standard practice is to inline callback functions if they're a single line.

For example, the following

`<ExampleComponent onClick={() => singleAction()} />
`
```
const complicatedCode = () => {
    firstAction();
    secondAction();
}
<ExampleComponent onClick={complicatedCode} />
```

2022-08-24 17:29 UTC, leestanley commented
Nice code review @farisashai 🐱

2022-08-27 04:49 UTC, farisashai approved these changes
Looks good!

Future changes to fix
- Mobile responsiveness
  - Statistics should wrap to the next row instead of squishing
  - Stars and description probably need to be stacked vertically

Ask Will about these
- Put real statistics in the last 2 entries or remove them
- More rotating text in the "Shoot for the stars" component

2022-08-27 04:56 UTC, merged