Faq Page
acmucsd/space-2022 pull request #7
Opened 2022-10-23 23:19 UTC by ryan-truong

2022-11-03 00:08 UTC, farisashai requested changes
Good start to the section! Couple of comments to look into

We're going to confirm that we base the UI on the Figma file and info doc before we publish this.

https://www.figma.com/file/AZizCmjAkXMR1K5iXtGAI2/SPACE-Wireframes?node-id=1427%3A873

https://docs.google.com/document/d/1YzgvCgc26EJdW0ExDlY5D5Ia1SbZLCJ8ZCJ72n2dhVQ/edit?usp=sharing

2022-11-03 00:08 UTC, farisashai commented on src/components/Faq/index.tsx
> +import React from "react";
tiny nitpick but we don't need to include this line in nextjs

2022-11-03 00:08 UTC, farisashai commented on src/sections/FAQ/faq.json
> +    ]
Nice idea to use a JSON file! This should make it super easy to swap out info on the page

2022-11-03 00:08 UTC, farisashai commented on src/components/Faq/index.tsx
> +const Faq: React.FC<panelData> = ({panelTitles, panelContent}) => {
1. Nitpick: Faq -> FAQ, panelData -> PanelData

2. This is more of a structural decision but it may be simpler to pass in the array of panel items directly as 

`const FAQ = ({ panelItems })`

where panelItems is the exact array from your JSON.

```
const panelItems = [
  {
    question: "What is Space?",
    answer: "Space is a career fair"
  }, 
]
```

In your JSON file, you already have the data structured as objects each containing everything necessary to display a single object which makes sense to keep it in one place.

If we do the same thing here, then we don't need to search through our array to find corresponding elements and risk the order being mismatched between the title and content arrays and we can precisely map through the objects

2022-11-03 00:08 UTC, farisashai commented on src/components/Faq/index.tsx
> +                      <div dangerouslySetInnerHTML={{ __html: panelContent[index]}}/>
let's avoid this attribute as often as we can 
`dangerouslySetInnerHTML={{ __html: panelContent[index]}}`
and try to set the content of the tag directly
`<div>{panelContent[index]}</div>`

2022-11-03 00:08 UTC, farisashai commented on src/sections/FAQ/index.tsx
> +  function activateStudents(){
We can remove the companies section with the new design

2022-11-05 22:20 UTC, farisashai requested changes
Functionality looks good! Let's remove the arrow image file and see if we can change the behavior to only expand one accordion at a time and make sure the code is clean

2022-11-05 22:20 UTC, farisashai commented on src/components/Faq/style.module.scss
> +// .faq {
Delete comments

2022-11-05 22:20 UTC, farisashai commented on src/components/Faq/style.module.scss
> +  a:hover{
We can combine duplicate selectors like

`a, a:visited, a:hover {}`

2022-11-05 22:20 UTC, farisashai commented on src/sections/Hero/style.module.scss
> +        background: #110F47;
Nitpick but let's try to use color variables to make sure we're referencing the exact color everywhere and can easily change when we need to

2022-11-05 22:20 UTC, farisashai commented on src/components/Faq/style.module.scss
> +  a{
Try to use class names to select specific elements

2022-11-05 22:20 UTC, farisashai commented on src/components/Faq/style.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Rubik&display=swap');
See if we can move font imports to import in _app to avoid duplication

2022-11-06 04:02 UTC, ryan-truong commented
The global font import ended up fixing the problem with MaterialUI. The latest commit adds font weight to the headers to match the wireframe.

Overall, FAQ page should be done now.

2022-11-06 23:58 UTC, farisashai approved these changes
Looks good!

2022-11-07 00:00 UTC, merged